### ISSUE TITLE
GTMOAuth2ViewControllerTouch.h file not found

### ISSUE THREAD

**Issue by footyapps27** [google/google-api-objectivec-client#165]
As per issue Issue #164 , I updated the pod to point to this repo. However, now I am getting the `'GTMOAuth2ViewControllerTouch.h' file not found` error. This was earlier used for logging in securely to the Google backend. 
Has this been removed in the new pod?

**Comment by thomasvl** [comment]
The pod doesn't directly depend on the OAuth2 support because some of the services can be used without authentication.  Additionally it can be used with the Identity Toolkit (for the folks that want that instead of the simpler OAuth2 UI).  So just add a dependency on https://github.com/google/gtm-oauth2/blob/master/GTMOAuth2.podspec to get OAuth2 if you want that dependency.

**Comment by footyapps27** [comment]
@thomasvl Thanks! I was successfully able to build the same.
