### ISSUE TITLE
Use of undeclared identifier 'GTMOAuth2ViewControllerTouch'

### ISSUE THREAD

**Issue by eraydiler** [google/google-api-objectivec-client#171]
Hi,

I added the library into the project using podfile with the command line `pod 'Google-API-Client' `

Pods were installed as they are supposed to be. (I guess).
But i cannot use GTMOAuth2ViewControllerTouch class because of compiler error.

`My import`
![screen shot 2016-03-29 at 16 59 07](https://cloud.githubusercontent.com/assets/1218603/14110437/199a5414-f5cf-11e5-81fe-536cb5ffa40e.png)
 
`Pods`
![screen shot 2016-03-29 at 16 53 56](https://cloud.githubusercontent.com/assets/1218603/14110248/5d00ea52-f5ce-11e5-9ca0-391de0ec8163.png)

`Compiler Error`
![screen shot 2016-03-29 at 16 50 40](https://cloud.githubusercontent.com/assets/1218603/14110139/e3987248-f5cd-11e5-89e8-ef566b7b847d.png)

**Comment by thomasvl** [comment]
This is basically a dup of issue #165 

The pod spec provided here is `GoogleAPIClient` - https://github.com/google/google-api-objectivec-client/blob/master/GoogleAPIClient.podspec I'm guessing you are getting a podspec made by someone else.

The pod doesn't directly depend on the OAuth2 support because some of the services can be used without authentication. Additionally it can be used with the Identity Toolkit (for the folks that want that instead of the simpler OAuth2 UI). So just add a dependency on https://github.com/google/gtm-oauth2/blob/master/GTMOAuth2.podspec to get OAuth2 if you want that dependency.

**Comment by eraydiler** [comment]
Thanks for answer, 

I changed my podFile and its now includes, pod 'GoogleAPIClient/Calendar' and pod 'GTMOAuth2' dependencies. But still getting the same compiler error when i try to use `GTMOAuth2ViewControllerTouch` class.

**Comment by thomasvl** [comment]
I'm not at a place I can pull to double check, but given the pod names, shouldn't the #import be GTMOAuth2/GTMOAuth2ViewControllerTouch.h not gtm-oauth2/GTMOAuth2ViewControllerTouch.h?

**Comment by eraydiler** [comment]
Updated the import statement as well. I is #import <GTMOAuth2/GTMOAuth2ViewControllerTouch.h>

`import`
![screen shot 2016-03-29 at 18 50 06](https://cloud.githubusercontent.com/assets/1218603/14114137/916ea1b6-f5de-11e5-93f1-121bffd8cb78.png)

**Comment by thomasvl** [comment]
@perotinus Any ideas while the pods wouldn't be working here?

**Comment by eraydiler** [comment]
Btw, my xcode version is 7.3. if it helps.

**Comment by thomasvl** [comment]
Anyone that looks at this, it moved over to https://github.com/google/gtm-oauth2/issues/62
