### ISSUE TITLE
Update docs for Cocoapods and auth dependency

### ISSUE THREAD

**Issue by dsanghan** [google/google-api-objectivec-client#191]
GTMSessionFetcher is listed as a dep, but not the gtm-oauth2 project.

If I manually also load gtm-oauth2 through cocoapods, they both reference a different GTMSessionFetcher podspec.

**Comment by thomasvl** [comment]
I need to tweak the docs.

Depending on what services you talk to (and which calls you make), you may not need authorization, so that's why it isn't a forced dep in the pod.

Likewise, you can actually use https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_authentication#method-detail as an authorizer if you are using that SDK. This last part came up in the comment on early drafts of the patch in https://github.com/google/google-api-objectivec-client/pull/157

**Comment by thomasvl** [comment]
Tweaked the description and keeping this open until I update things accordingly.

**Comment by dsanghan** [comment]
Ok. I'm using gtm-oauth2 on osx separately and now integrating the client apis so that's a no go. I'll manually integrate the project since gtm-oauth2 already has the GTMSessionFetcher as a dep.

**Comment by thomasvl** [comment]
Sorry, didn't follow your last comment.  Did you just mean using the identity key is a no go?  You don't have to use it, the reason the podspec for this library doesn't depend on either is because you can use either one, and we didn't want to force it.  You should be able to depend on this pod and the gtm-oauth2 one just fine.

**Comment by thomasvl** [comment]
Updated the building wiki https://github.com/google/google-api-objectivec-client/wiki/BuildingTheLibrary with the note about auth not include.

And sorry for not noticing before, the `gtm-oauth2` spec isn't controlled by us.  [GTM OAuth 2](https://github.com/google/gtm-oauth2) provides a spec named `GTMOAuth2`.  Using that should leave you with a single dependency for for the SessionFetcher.

**Comment by dsanghan** [comment]
Yeah noticed that. Thanks for the quick response!
