### ISSUE TITLE
Ordered Blogger comments

### ISSUE THREAD

**Issue by puelocesar** [google/google-api-objectivec-client#198]
I need to download only the most recent comments from a Blog, but [GTLQueryBlogger queryForCommentsListByBlogWithBlogId:blogID] doesn't support orderBy.

**Comment by thomasvl** [comment]
Looks like that api instead uses a startDate/endDate model, so you'd have to keep track of last time you got comments and ask for comments since that time.

On the bottom of the [API page](https://developers.google.com/blogger/docs/3.0/getting_started), there's a section labeled _Connect_ which lists a forum and G+ community.  You might want to try those since your question isn't really specific to ObjC and is more about the server provided API in general.
