### ISSUE TITLE
Best method for adding Google Auth 

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client#217]
Great job on making this project easier to build @thomasvl - I managed to get it working really quickly.  

As a bit of feedback - whats the recommended method to use for Auth for new projects.  I am using the Search Console APi for a work project. 

Should I use the Google Signin SDK or or the Google Auth Library? 
Signin SDK seems more developed but the GTMAuth seems much simpler( the version you used in this projects examples)

**Comment by thomasvl** [comment]
First up (and I was about to post this on the other issue), you really want to use GTLR instead of GTL:
> https://github.com/google/google-api-objectivec-client-for-rest
The new project use REST (with JSON) instead of JSON+RPC.  A growing number of our APIs were only doing REST, so this allow us to support a more complete set.

As to why it is a new project vs. just a revision to this one.  The apis aren't an exact match, so migrating code can be tricky; if someone directly used GTL but had a dependency that also used it, they would have to get both migrated at once.  So by making it a new project, they two can be migrated independently.

As far as your auth question - The [wiki](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization) covers both options; the samples use GTMAppAuth.  I personally don't have much experience with the Sign-In library, I'd probably go with GTMAppAuth just because it is all source and that might make it a little easier to integrate, etc.
