### ISSUE TITLE
GTLDriveFileList does not implement the items property, which means auto-paging does not work

### ISSUE THREAD

**Issue by streeter** [google/google-api-objectivec-client#219]
When making a query as in the Objective-C example in https://developers.google.com/drive/v2/reference/files/list, the response populates the `files` property on the `GTLDriveFileList` object. However, [the `GTLService` expects there to be an `items` property](https://github.com/google/google-api-objectivec-client/blob/0a3d6d635b9db2198f03ed062a7b85824d2930bd/Source/Objects/GTLService.m#L1724) in order to auto-page.

The current solution is to fetch a larger max number of pages, and hope that there are fewer than 1000 items in the drive's folder.

**Comment by thomasvl** [comment]
First up I'd suggest you migrate to GTLR as GTL has been [deprecated](https://github.com/google/google-api-objectivec-client#warning-deprecation-notice).

One of the things we did in GTLR is make the paging support a little more generic, so cases where there is a single collection within the object, auto paging should also "just work" because the library picks off this single collection and the query arguments.

In general the paging just just some extra code that collects the _nextPageToken_ off the results and set it as the _pageToken_ on the query and issues that new query to get the next set of results.  It then merges the lists of results into a single one.  So you should be able to do this manually yourself.  In some cases, it is better to actually do this merging yourself as you then only have to fetch the later pages if your user scrolls to the point they are needed; that sorta on demand behavior yourself actually means you get results faster as you only need a subset, and it means you need less data bandwidth as you are only fetching what your user ends up interacting with.

**Comment by streeter** [comment]
Oh, thanks for the link @thomasvl! Appreciate it. I'm happy to migrate to GTLR instead.

I'm happy to close this since the repo is deprecated.

**Comment by thomasvl** [comment]
Thanks!
