### ISSUE TITLE
GTMHTTPDebugLogs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#39]
```
What steps will reproduce the problem?
1. [GTMHTTPFetcher setLoggingEnabled:YES];
2. Use various GTL calls which generate logs on the device
3. Open iTunes, go to device, Apps, File Sharing, Documents folder for app - 
can't download folder, permission denied

What is the expected output? What do you see instead?
Ability to download these logs without having to download the whole app via 
xcode. Unfortunately iTunes doesn't allow it to be downloaded due to folder 
permissions (S_IRWXU)

```

Original issue reported on code.google.com by `jhalst...@gmail.com` on 2 Jul 2013 at 4:38

**Comment by thomasvl** [comment]
Closing this out since it was migrated from code.google.com.

Downloading via iTunes is always going to be a little hard since Apple doesn't consider that a dev tool.  Within Xcode you can use the Organizer to inspect subparts of an app, download the logs folder.

If you really wanted to support better download via iTunes, you can use the API to change the logging location, and log to the documents directory.  You just need to ensure you set up the logging directory so it doesn't get backed up, etc. wasting users data and iCloud storage.
