### ISSUE TITLE
Duplicate definitions on importing Plus Sign In, OAuth2 and Storage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#89]
```
What steps will reproduce the problem?

1. Create a new Swift iOS project using the Podfile:

pod 'google-plus-ios-sdk', '~> 1.7.1'
pod 'Google-API-Client', '~> 1.0.422'

2. Creating a bridging header:

#import <GoogleOpenSource/GTMOAuth2Authentication.h>

#import <GooglePlus/GPPSignIn.h>
#import <GooglePlus/GPPSignInButton.h>
#import <GooglePlus/GPPURLHandler.h>

#import "GTLApi.h"
#import <Google-API-Client/GTLStorage.h>

3. Build

What is the expected output? What do you see instead?

Build errors attached.


What version of the product are you using? On what operating system?

API client 1.0.422, XCode 6.4, Cocoapods 0.37.1, Mac OSX 10.10.4


Please provide any additional information below.


```

Original issue reported on code.google.com by `1...@eliotstock.com` on 8 Aug 2015 at 7:06

Attachments:
- [build_errors.txt](https://storage.googleapis.com/google-code-attachments/google-api-objectivec-client/issue-89/comment-0/build_errors.txt)

**Comment by eliotstock** [comment]
The problem here is not Plus or OAuth2, it's this:

#import "GTLApi.h"

This is a client for a Google Cloud Endpoints API, generated using the ServiceGenerator project from Google. That project already imports GTLObject.h. When that file is also imported by:

#import <Google-API-Client/GTLStorage.h>

the build fails.

How should the Google API client project coexist with a Google Cloud Endpoints client library?

**Comment by thomasvl** [comment]
Sounds like the problem might be the headers are getting included via different methods (`#import <>` vs. `@include ""`) so the compiler doesn't consider them to be the "same", and includes them again causing the duplicates.

The pods in the original report also aren't the official pods from the github projects, so they could be doing odd things/pulling different sources then what are here.
